<link rel="stylesheet" id="e-animations-css" href="https://glbbestjapan.com/wp-content/plugins/elementor/assets/lib/animations/animations.min.css?ver=3.6.7" type="text/css" media="all">
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/themes/agent_tcd033/includes/js/skip-link-focus-fix.js?ver=20130115" id="_tk-skip-link-focus-fix-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-includes/js/wp-embed.min.js?ver=5.7.1" id="wp-embed-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-includes/js/comment-reply.min.js?ver=5.7.1" id="comment-reply-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/js/webpack.runtime.min.js?ver=3.6.7" id="elementor-webpack-runtime-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/js/frontend-modules.min.js?ver=3.6.7" id="elementor-frontend-modules-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/lib/waypoints/waypoints.min.js?ver=4.0.2" id="elementor-waypoints-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-includes/js/jquery/ui/core.min.js?ver=1.12.1" id="jquery-ui-core-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/lib/swiper/swiper.min.js?ver=5.3.6" id="swiper-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/lib/share-link/share-link.min.js?ver=3.6.7" id="share-link-js"></script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/lib/dialog/dialog.min.js?ver=4.9.0" id="elementor-dialog-js"></script>
<script type="text/javascript" id="elementor-frontend-js-before">
var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false,"isScriptDebug":false},"i18n":{"shareOnFacebook":"Facebook \u3067\u5171\u6709","shareOnTwitter":"Twitter \u3067\u5171\u6709","pinIt":"\u30d4\u30f3\u3059\u308b","download":"\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9","downloadImage":"\u753b\u50cf\u3092\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9","fullscreen":"\u30d5\u30eb\u30b9\u30af\u30ea\u30fc\u30f3","zoom":"\u30ba\u30fc\u30e0","share":"\u30b7\u30a7\u30a2","playVideo":"\u52d5\u753b\u518d\u751f","previous":"\u524d","next":"\u6b21","close":"\u9589\u3058\u308b"},"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"responsive":{"breakpoints":{"mobile":{"label":"\u30e2\u30d0\u30a4\u30eb","value":767,"default_value":767,"direction":"max","is_enabled":true},"mobile_extra":{"label":"Mobile Extra","value":880,"default_value":880,"direction":"max","is_enabled":false},"tablet":{"label":"\u30bf\u30d6\u30ec\u30c3\u30c8","value":1024,"default_value":1024,"direction":"max","is_enabled":true},"tablet_extra":{"label":"Tablet Extra","value":1200,"default_value":1200,"direction":"max","is_enabled":false},"laptop":{"label":"\u30ce\u30fc\u30c8\u30d6\u30c3\u30af","value":1366,"default_value":1366,"direction":"max","is_enabled":false},"widescreen":{"label":"\u30ef\u30a4\u30c9\u30b9\u30af\u30ea\u30fc\u30f3","value":2400,"default_value":2400,"direction":"min","is_enabled":false}}},"version":"3.6.7","is_static":false,"experimentalFeatures":{"e_import_export":true,"e_hidden_wordpress_widgets":true,"landing-pages":true,"elements-color-picker":true,"favorite-widgets":true,"admin-top-bar":true},"urls":{"assets":"https:\/\/glbbestjapan.com\/wp-content\/plugins\/elementor\/assets\/"},"settings":{"page":[],"editorPreferences":[]},"kit":{"global_image_lightbox":"yes","active_breakpoints":["viewport_mobile","viewport_tablet"],"lightbox_enable_counter":"yes","lightbox_enable_fullscreen":"yes","lightbox_enable_zoom":"yes","lightbox_enable_share":"yes","lightbox_title_src":"title","lightbox_description_src":"description"},"post":{"id":150,"title":"Global%20Best%20Japan%E3%81%A8%E3%81%AF%20%E2%80%93%20Global%20Best%20Japan","excerpt":"","featuredImage":false}};
</script>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/js/frontend.min.js?ver=3.6.7" id="elementor-frontend-js"></script><span id="elementor-device-mode" class="elementor-screen-only"></span>
<script type="text/javascript" src="https://glbbestjapan.com/wp-content/plugins/elementor/assets/js/preloaded-modules.min.js?ver=3.6.7" id="preloaded-modules-js"></script><svg style="display: none;" class="e-font-icon-svg-symbols"></svg>